apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-next-config
data:
  # Non-sensitive environment variables
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_SECURE: "false"
  MAIL_FROM: "noreply@yourdomain.com"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM: "noreply@yourdomain.com"
  NEXT_PUBLIC_BETTER_AUTH_URL: "http://auth-next-service:3000"  # K8s service URL
  BETTER_AUTH_URL: "http://auth-next-service:3000"  # K8s service URL
