apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-next-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-next
  template:
    metadata:
      labels:
        app: auth-next
    spec:
      containers:
      - name: auth-next
        image: luza999/auth-next:latest 
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: auth-next-config
        - secretRef:
            name: auth-next-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
