apiVersion: v1
kind: Secret
metadata:
  name: auth-next-secret
type: Opaque
data:
  # Base64 encoded sensitive environment variables
  MONGODB_URI: "bW9uZ29kYitzcnY6Ly9hbGxvdWNoYXltYW4yMTo2VU9VUDhNMU9Na0xXeUlDQGNsdXN0ZXIwLnV5b3djaXUubW9uZ29kYi5uZXQvdXNlcnM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA="
  BETTER_AUTH_SECRET: "eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmUtbWluaW11bS0zMi1jaGFyYWN0ZXJz"
  RESEND_API_KEY: "cmVfSFpWeGMxYUdfe0hodGtmR2JqMWhyYWdwOXVpa0hDNDQ="
  MAIL_USER: "YWxsb3VjaGF5bWFuNzBAZ21haWwuY29t"
  MAIL_PASS: "a3NrYXhnb21jb3h2enhxbw=="
  SMTP_USER: "YWxsb3VjaGF5bWFuNzBAZ21haWwuY29t"
  SMTP_PASS: "a3NrYXhnb21jb3h2enhxbw=="
  CLOUDINARY_CLOUD_NAME: "ZHpyc2JqZG1h"
  CLOUDINARY_API_KEY: "MTExNzIzNTkzODU4Mjgy"
  CLOUDINARY_API_SECRET: "QXlWeEltMzRqY19TUzlrSWdCT3lYYzNEUXhB"
